# Generated by Django 5.0.3 on 2026-03-18 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('tenant', 'Tenant'), ('attorney', 'Attorney')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('property_address', models.TextField(blank=True)),
                ('county', models.CharField(blank=True, choices=[('davidson', 'Davidson County'), ('shelby', 'Shelby County'), ('knox', 'Knox County'), ('hamilton', 'Hamilton County'), ('other', 'Other Tennessee County')], max_length=50)),
                ('landlord_name', models.CharField(blank=True, max_length=255)),
                ('landlord_contact', models.CharField(blank=True, max_length=255)),
                ('issue_type', models.CharField(blank=True, choices=[('eviction', 'Eviction / Unlawful Detainer'), ('habitability', 'Habitability / Repairs'), ('security_deposit', 'Security Deposit Dispute'), ('harassment', 'Landlord Harassment'), ('discrimination', 'Housing Discrimination'), ('lease_dispute', 'Lease Dispute'), ('other', 'Other')], max_length=50)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('issue_description', models.TextField(blank=True)),
                ('bar_number', models.CharField(blank=True, max_length=50)),
                ('firm_name', models.CharField(blank=True, max_length=255)),
                ('case_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('lease', 'Lease Agreement'), ('eviction_notice', 'Eviction Notice'), ('correspondence', 'Correspondence / Letters'), ('photo', 'Photo / Visual Evidence'), ('court_filing', 'Court Filing'), ('payment_record', 'Payment Record'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='intake/documents/')),
                ('original_filename', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='intake.intakesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='CaseNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('facts', models.JSONField(default=list)),
                ('timeline', models.JSONField(default=list)),
                ('key_terms', models.JSONField(default=list)),
                ('disputed_points', models.JSONField(default=list)),
                ('open_questions', models.JSONField(default=list)),
                ('urgent_deadlines', models.JSONField(default=list)),
                ('recommended_next_steps', models.JSONField(default=list)),
                ('raw_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notebook', to='intake.intakesubmission')),
            ],
        ),
    ]
